In [1]:
import sys
import pandas as pd
import numpy as np
import random as rn
from torchBertEmbedding import embedTweets,cosine_similarity
from pytorch_pretrained_bert import BertTokenizer
from pytorch_pretrained_bert import BertModel

Using TensorFlow backend.


In [2]:
df = pd.read_csv('2012_6_events_removed_nonEnglish.csv',sep='\t')
df.head()

Id        Username  \
0  261547192714670082   JhenlEvabless   
1  261547247601319936    yonkersoem40   
2  261547683091714049  washingtonpost   
3  261547473980510208         88Timez   
4  261547721998082048      JaneShmame   

                                                text   Timestamp  NumberOfRT  \
0  @Digicel_Jamaica...they never failed during sa...  1351146480           3   
1  RT @NYSDHSES: #NYS #EOC activating Saturday fo...  1351143780           2   
2  4 Hurricane Sandy scenarios for D.C.: http://w...  1351147500          43   
3  I Personally Blame The Government Of The Baham...  1351147200           2   
4  @HandySandie “ @rtenews: Hurricane Sandy hits ...  1351113900           1   

   NumberOfForward                                        text_tokens  \
0                1  ['digicel_jamaica', 'never', 'fail', 'dure', '...   
1                2  ['nysdhs', 'nys', 'eoc', 'activ', 'saturday', ...   
2                3  ['hurrican', 'sandi', 'scenario', 'http', 'wap...   
3                2   ['person', 'blame', 'govern', 'bahama', 'sandi']   
4                0  ['handysandi', 'rtenew', 'hurrican', 'sandi', ...   

                                            sentance  
0  digicel_jamaica never fail dure sandi mentiont...  
1  nysdhs nys eoc activ saturday strateg plan res...  
2  hurrican sandi scenario http wapo suiud via ca...  
3                   person blame govern bahama sandi  
4  handysandi rtenew hurrican sandi hit southeast...

In [3]:
documents = []
for sent in df.sentance:
    documents.append(sent)

In [4]:
%%time
pool_embed_tweet = None
bert = BertModel.from_pretrained('bert-base-uncased')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
for i in range(0,200,100):
    embed_tweet = embedTweets(documents[i:i+100],bert,tokenizer)
    if i == 0:
        pool_embed_tweet = embed_tweet
    else:
        pool_embed_tweet = np.vstack((pool_embed_tweet,embed_tweet))


CPU times: user 1min 3s, sys: 23.6 s, total: 1min 26s
Wall time: 23.9 s


In [5]:
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(pool_embed_tweet, pool_embed_tweet))

[[0.99999994 0.97178626 0.92504525 ... 0.9275969  0.91177106 0.98805594]
 [0.97178626 1.0000002  0.97246194 ... 0.9578161  0.9667164  0.9559363 ]
 [0.92504525 0.97246194 0.9999993  ... 0.9295991  0.979487   0.90504223]
 ...
 [0.9275969  0.9578161  0.9295991  ... 0.99999994 0.94320834 0.89756817]
 [0.91177106 0.9667164  0.979487   ... 0.94320834 0.99999964 0.88834447]
 [0.98805594 0.9559363  0.90504223 ... 0.89756817 0.88834447 1.0000001 ]]
